### ISSUE TITLE
(Feature Request) Support for Radxa CM5

### ISSUE THREAD

**Issue by kerta1n** [EvanKrall/pipad#28]
Hello, with the upcoming [CM5](https://www.cnx-software.com/2022/09/08/radxa-cm5-rockchip-rk3588s-module-raspberry-pi-cm4/) board with a RK3588S (which is an Octa-core CPU), would all of the I/O on this PCB be compatible if someone wants to use this as a faster replacement to the RPi CM4?
edit: spelling mistake

**Comment by EvanKrall** [comment]
In theory, yes, as long as the pins are in compatible locations.

I'm using the majority of the pins as low speed GPIO (interrupts and enable pins and such), I wouldn't be too concerned with those.

the special-purpose pins I'm using are:
- i2c
- I2s
- PWM (for LCD backlight)
- PCIe, but this is optional if you use built-in eMMC
- DSI
- USB

As long as the pins I'm using for those can be used for the same purpose with the CM5 (and there isn't some other weirdness with them), it should work? You'd have to rewrite the device trees and such.

I do also have a branch (radxa_cm3) specifically designed for the Radxa CM3, which takes advantage of the fact that the CM3 can output LVDS signals directly, and avoids the need for the DSI-LVDS bridge. It doesn't look like the CM5 can do LVDS, so one would need to start from the cm4 branch.

Also it looks like the CM5 doesn't have wifi, so I'd need to figure out the iPad's built in wifi chip to have networking. (Currently I'm just relying on the cm4's built-in wifi)

If you're planning on ordering a copy of this board, I wouldn't really recommend it. It's very much a work in progresss. I've still got several issues to work out, the biggest of which is getting the screen to work. I've been posting updates to https://hackaday.io/project/177256-put-a-raspberry-pi-cm4-into-an-original-ipad (but I'm currently stuck on getting the LVDS bridge to cooperate)

**Comment by kerta1n** [comment]
That makes a lot more sense. Thank you!
